Log message for timeout error when loading model artefacts
NVIDIA/earth2studio pull request #142
Opened 2024-09-26 17:20 UTC by gertln

# Earth2Studio Pull Request

## Description

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/earth2studio/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/earth2studio/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/earth2studio/issues) is linked to this pull request.

## Dependencies

2024-11-05 09:44 UTC, dallasfoster commented
/blossom-ci

2024-11-05 09:50 UTC, dallasfoster commented
/blossom-ci

2024-11-13 07:43 UTC, dallasfoster requested changes

2024-11-13 07:43 UTC, dallasfoster commented on earth2studio/models/auto/package.py
> +                    logger.error(m)
Looks like a linting error. From your local copy of the project directory, please run `make setup-ci` and `make lint`.

2024-11-21 16:20 UTC, NickGeneva commented
Closing, added in https://github.com/NVIDIA/earth2studio/pull/155

Thanks!

2024-11-21 16:20 UTC, closed without merging